name: test

on:
  workflow_dispatch

jobs:
    gradle_build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up JDK 17
              uses: actions/setup-java@v2
              with:
                java-version: '17'
                distribution: 'temurin'
                
            - name: chmod jar file
              run: chmod +x ./gradlew
              
            - name: Build with Gradle
              run: ./gradlew build

            - name: list build directory
              run: ls -l ./build/libs
            
            - name: chmod jar file
              run: chmod +x ./build/libs/gradle-0.0.1-SNAPSHOT.jar
            
            - name: run springboot jar
              run: | 
                java -jar ./build/libs/gradle-0.0.1-SNAPSHOT.jar & 
                sleep 20
              
            - name: run automated test
              run: |
                curl -X GET http://localhost:8080/
