name: docker hub pull

on:
  workflow_dispatch

jobs:
    docker-hub-pull:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: docker pull and run
              run: |
                docker pull ${{ secrets.DOCKER_USERNAME }}/my-image:latest
                docker run -d --name my-container ${{ secrets.DOCKER_USERNAME }}/my-image:latest
            - name: docker operations
              run: |
                docker ps -a
                docker logs my-container

            - name: logout from docker hub
              if: always()
              run: |
                docker logout
