name: docker file build

on:
  workflow_dispatch

jobs:
    docker-file-build:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
        
            - name: Build Docker image
              uses: docker/build-push-action@v5
              with:
                context: .
                file: Dockerfile
                push: false
                load: true
                tags: my-image:latest
                cache-from: type=gha
                cache-to: type=gha,mode=max
        
            - name: run Docker container
              run: |
                docker run -d -p 8080:8080 my-image:latest
                sleep 15

                docker ps
                docker logs $(docker ps -lq)
                
            - name: run automated test
              run: |
                curl -X GET http://localhost:8080/
