name: docker hub

on:
  workflow_dispatch

jobs:
    docker-hub:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: login to docker hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}
            
            - name: docker operations
              run: |
                docker build -t my-image:latest .
                docker tag my-image:latest ${{ secrets.DOCKER_USERNAME }}/my-image:latest
                docker push ${{ secrets.DOCKER_USERNAME }}/my-image:latest
           
            - name: logout from docker hub
              if: always()
              run: |
                docker logout
            
